### PR TITLE
Import latest default consul.hcl

### PR DESCRIPTION
**Pull request by hollow**
I have imported the latest `consul.hcl` from HashiCorp - primarily to fix the warning about deprecated `ui=` config. While at it I have also 

- changed the default `consul_server` to `no` since IMO you usually want to install consul clients and only explicitly setup consul servers once in the beginning
- relaxed the assertions to accept `consul_bootstrap_expect` as a string for compatibility with when Jinja only returns strings, e.g. using the following variables:

```
consul_retry_join: "{{ consul_servers | map('extract', hostvars, ['private_ipv4']) | list }}"
consul_bootstrap_expect: "{{ consul_retry_join | length }}"
```

I failed to find a way to force this into a number and according to https://github.com/ansible/ansible/issues/30366 this is not possible...

### CODE REVIEW

**Comment by hollow** [comment]
@robertdebock unfortunately I've opened this PR against our master branch, so it now includes changes that were not supposed to be sent your way / that you might not want merged (i.e. `consul_extra_config`). can you merge everything up to [bbf415e](https://github.com/robertdebock/ansible-role-consul/pull/1/commits/bbf415e268be0aadaeac298802989147014c2a45) so we don't add more and more commits to this PR or should I open a new PR?

**Comment by robertdebock** [comment]
Hi, sorry for forgetting about this PR.

I'll let CI run and merge on success.

**Comment by robertdebock** [comment]
I guess there is a typo in the configuration file somewhere:

```
RUNNING HANDLER [ansible-role-consul : restart consul] *************************
[1508](https://github.com/robertdebock/ansible-role-consul/runs/5300320575?check_suite_focus=true#step:6:1508)
fatal: [consul-amazonlinux-latestpy310-ansible-5]: FAILED! => {"changed": false, "msg": "Unable to start service consul: Job for consul.service failed because start of the service was attempted too often. See \"systemctl status consul.service\" and \"journalctl -xe\" for details.\nTo force a start use \"systemctl reset-failed consul.service\" followed by \"systemctl start consul.service\" again.\n"}
[1509](https://github.com/robertdebock/ansible-role-consul/runs/5300320575?check_suite_focus=true#step:6:1509)
```

Can you have a look?

**Comment by hollow** [comment]
https://github.com/robertdebock/ansible-role-consul/pull/2

**Pull request closed without merging**
